---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-org-cert
  namespace: default
spec:
  dnsNames:
    - example.org
  secretName: example-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer